
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Customize below

environment:
  global:
    NOT_CRAN: true
    USE_RTOOLS: true
    R_CHECK_ARGS: --no-build-vignettes --no-manual
    GITHUB_PAT:
      secure: tJ7T62qzDAM58XyadTuFzqT5bApwLjbKysX6Jll+WJKkBLsXccmI724201RCpWIy

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

notifications:
   - provider: Slack
     auth_token:
       secure: lo2pvFaAGQsvWkuRClDc2Fsqd6SiOAi/yHC/gur3fdgBCueEBMmRkxBf4nTsnqmSBEcoBqz3HjXvszO0Q3WV3Q==
     channel: '#builds'
     on_build_failure: true
     on_build_status_changed: true

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: tar

  - path: '\*_*.zip'
    name: zip